name: Playpen Release

on:
  pull_request:
    types: [closed]
    paths:
      - '.github/project.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  release:
    runs-on: ubuntu-latest
    name: release
    if: ${{github.event.pull_request.merged == true}}
    outputs:
      tag: ${{ steps.metadata.outputs.current-version }}
    steps:
      - uses: radcortez/project-metadata-action@main
        name: Retrieve project metadata
        id: metadata
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          metadata-file-path: '.github/project.yml'

      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: 'maven'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Configure Git author
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      - name: Maven release ${{steps.metadata.outputs.current-version}}
        run: |
          find -name '*.md' -exec sed -i 's/${{steps.metadata.outputs.next-version}}/${{steps.metadata.outputs.current-version}}/g' {} +
          find -name '*.md' -exec sed -i 's|raw.githubusercontent.com/quarkiverse/quarkus-playpen/main|raw.githubusercontent.com/quarkiverse/quarkus-playpen/${{steps.metadata.outputs.current-version}}|g' {} +
          git commit -a -m "Bump doc to current version"
          mvn -B release:prepare -Prelease -DreleaseVersion=${{steps.metadata.outputs.current-version}} -DdevelopmentVersion=${{steps.metadata.outputs.next-version}}
          mvn -B release:perform -Darguments=-DperformRelease -DperformRelease -Prelease
          find -name '*.md' -exec sed -i 's|raw.githubusercontent.com/quarkiverse/quarkus-playpen/${{steps.metadata.outputs.current-version}}|raw.githubusercontent.com/quarkiverse/quarkus-playpen/main|g' {} +
          find -name '*.md' -exec sed -i 's/${{steps.metadata.outputs.current-version}}/${{steps.metadata.outputs.next-version}}/g' {} +
          git commit -a -m "Bump doc to next-version"
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Push changes to ${{github.base_ref}} branch
        run: |
          git push
          git push origin ${{steps.metadata.outputs.current-version}}
  cli-binary:
    name: Quarkus CLI binary on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: release
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Build CLI Binaries ${{ needs.release.outputs.tag }}
        run: |
          git checkout ${{ needs.release.outputs.tag }}
          mvn clean install -DskipTests=true -Dnative -pl :playpen-core,:kubernetes-playpen-core,:playpen-cli
          mv cli/target/playpen-cli-*-runner${{ matrix.os == 'windows-latest' && '.exe' || '' }} playpen.${{ matrix.os }}${{ matrix.os == 'windows-latest' && '.exe' || '' }}

      - name: Release binary ${{ needs.release.outputs.tag }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.release.outputs.tag }}
          files: playpen.${{ matrix.os }}${{ matrix.os == 'windows-latest' && '.exe' || '' }}
