name: Build CLI Binaries

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

defaults:
  run:
    shell: bash

jobs:
  cli-binary:
    name: Quarkus CLI binary on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v4

      - name: read-yaml-file
        uses: pietrobolcato/action-read-yaml@1.1.0
        id: project
        with:
          config: ${{ github.workspace }}/.github/project.yml

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Build CLI Binaries ${{ steps.project.outputs['release.current-version'] }}
        run: |
          git checkout ${{ steps.project.outputs['release.current-version'] }}
          mvn clean install -DskipTests=true -Dnative -pl :playpen-core,:kubernetes-playpen-core,:playpen-cli


      - name: Release binary ${{ steps.project.outputs['release.current-version'] }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.project.outputs['release.current-version'] }}
          files: cli/target/playpen-cli-*-runner
